services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '10081:81'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - nginx_network  

volumes:
  data_backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker/ingress/data
  letsencrypt_backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker/ingress/letsencrypt

networks:
  nginx_network:
    driver: bridge
